# Generated by Django 5.0 on 2024-01-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('format', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('duration_secs', models.IntegerField(default=0)),
            ],
        ),
    ]
